import type { NextPage } from "next";
import Head from "next/head";
import { Text } from "@chakra-ui/react";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text fontSize="6xl">CrazyStack ReactJs</Text>
    </div>
  );
};

export default Home;
